{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "iozone.serviceAccountName" . }}
  labels:
{{ include "iozone.labels" . | indent 4 }}
{{- end -}}
